version: '3.7'
services:
  nginx:
    image: nginx:1.24.0
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - postgre
    networks:
      - pyeditorial_network

  postgres:
    image: postgres:14.8
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=great123
      - POSTGRES_DB=pyeditorialdb
    volumes:
      #- ./pgdata:/var/lib/postgresql/data
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - pyeditorial_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    networks:
      - pyeditorial_network

networks:
    pyeditorial_network: