version: '3.7'
services:
  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - pyeditorial

  postgres:
    image: postgres:14.8
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=great123
      - POSTGRES_DB=pyeditorialdb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pyeditorial

  web:
    build:
     context: .
     dockerfile: Dockerfile
    container_name: app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - pyeditorial

networks:
  pyeditorial:
    name: pyeditorial