version: '3.7'
services:
  postgres:
    image: postgres:14.8
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=great123
      - POSTGRES_DB=pyeditorialdb
    volumes:
      #- ./pgdata:/var/lib/postgresql/data
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - pyeditorial

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    networks:
      - pyeditorial

networks:
  pyeditorial:
    name: pyeditorial